from dataclasses import dataclass
from uuid import uuid4


@dataclass(frozen=True)
class ItemFactory:
    title_prefix: str = "API generated item"

    def build(self) -> dict[str, object]:
        suffix = uuid4().hex[:8]
        return {
            "title": f"{self.title_prefix} {suffix}",
            "description": f"Generated by pytest API coverage for CRUD validation {suffix}.",
            "tags": ["api", "pytest"],
        }
